
version: 2

models:
    - name: dim_customers
      description: "Build dim customers"
      columns:
          - name: id
            description: "Build dim customers"
            tests:
                - unique
                - not_null

